CREATE TABLE languages(
  code CHAR(2) NOT NULL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE words(
  id NUMERIC NOT NULL PRIMARY KEY,
  language CHAR(2) NOT NULL REFERENCES languages,
  name TEXT UNIQUE NOT NULL
);